# 상위 공통 코드
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CS','CONTRACT_STATUS','계약 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AP','AUTHORIZATION_PROCESS','승인 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AS','ACCOUNT_STATUS','계좌 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('RG','REGION','지역', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('TX','TRANSACTION','거래 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('BK','BANK','은행 코드', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CD','CARD','카드', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AC','ACCOUNT','계좌', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('BR','BRANCH','지점', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('PD','PRODUCT','상품', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('OD','OVERDUE','연체', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('IN','INSURANCE','보험', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('LN','LOAN','대출', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('RT','RATE','금리', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('FX','FOREIGN_EXCHANGE','외환', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('DO','DEPOSIT','예/적금', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CO','COUNSELING','상담', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('PA','PARTNER','제휴사', CURRENT_TIMESTAMP);

# 하위 공통 코드
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD001','TRANSPORTATION CARD','교통카드','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD002','CASHBACK','캐시백','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD003','POINT','포인트','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD004','OVERSEAS','해외 결제','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD006','ACTIVE','정상','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD007','SUSPENDED','거래정지','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD008','LOST','분실','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD009','CANCELLED','해지','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD010','EXPIRED','만료','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD016','SCHEDULED','예정','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD017','BILLED','청구 완료','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD018','PAID','납부 완료','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD019','OVERDUE','연체','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD020','REFUNDED','환불','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD026','GENERATED','생성','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD027','BILLED','발행','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD028','PAID','완납','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD029','OVERDUE','연체','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','CD030','CLOSED','종료','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','AC001','BOTH','제한 없음','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','AC002','DEPOSIT_ONLY','입금 전용','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','AC003','WITHDRAW_ONLY','출금 전용','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','BR001','OPEN','영업중','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','BR002','CLOSED','영업종료','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','BR003','SUSPENDED','휴점','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD001','PAPER','지류','서류 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD002','ELECTRONIC','디지털','서류 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD006','DEPOSIT','예적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD007','LOAN','대출','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD008','CARD','카드','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','PD009','INSURANCE','보험','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','OD001','LOAN','대출','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','OD002','CARD','카드','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','OD003','INSURANCE','보험','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN001','TERMINATED','해지','해지/만기 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN002','EXPIRED','만기','해지/만기 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN006','WHOLE_LIFE','종신보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN007','TERM_LIFE','정기보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN008','ENDOWMENT','저축성/만기환급형 보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN009','UNIVERSAL','유니버셜보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN010','VARIABLE_LIFE','변액보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN011','ANNUITY','연금보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN012','ANNUITY_VARIABLE','변액연금보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN013','HEALTH','건강보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN014','CANCER','암보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN015','CRITICAL_ILLNESS','중대질병(CI) 보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN016','MEDICAL','의료실비보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN017','ACCIDENT','상해보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN018','DRIVER','운전자보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN019','TRAVEL','여행자보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN020','FIRE','화재보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN021','HOME','주택/가재도구보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN022','AUTO','자동차보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN023','PET','반려동물보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN024','LIABILITY','배상책임보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','IN025','GROUP','단체보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN001','EQUAL_INSTALLMENT','원리금 균등 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN002','EQUAL_PRINCIPAL','원금 균등 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN003','LUMP_SUM','만기 일시 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN004','GRACE','거치식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN005','MIXED','혼합 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN006','REVOLVING','자유 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN007','STEP_UP','체중식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','LN008','STIP_DOWN','체감식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','RT001','DISCOUNT','우대금리','금리 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','RT002','ADDITIONAL','가산금리','금리 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','RT006','DEPOSIT','예/적금','금리 적용 상품 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','RT007','LOAN','대출','금리 적용 상품 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX001','EXCHANGE','환전','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX002','RE_EXCHANGE','재환전','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX003','TRANSFER','이체','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX004','PURCHASE','매입','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX006','TUITION_EXPENSES','유학 경비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX007','LIVING_EXPENSES','해외 체재비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX008','TRAVEL_EXPENSES','여행 경비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX009','GIFT/DONATION_REMITTANCE','증여 송금','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX010','TRADE_SETTLEMENT','무역거래','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX011','OVERSEAS_DIRECT_INV','해외 직접 투자','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX012','REAL_ESTATE_ACQ','부동산 취급','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','FX013','OVERSEAS_DEPOSIT','해외 예금','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO001','DEMAND_DEPOSIT','요구불 예금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO002','TIME_DEPOSIT','정기 예금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO003','FIXED_SAVING','정기 적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO004','FREE_SAVING','자유 적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO016','DAY','일','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO017','MONTH','월','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO018','YEAR','년','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO021','MATURITY','만기 지급','이자 지급 주기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO022','MONTHLY','월 지급','이자 지급 주기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO026','SIMPLE','단리','이자 계산 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','DO027','COMPOUND','복리','이자 계산 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO001','LOAN','대출 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO002','DEPOSIT','예적금 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO003','CARD','카드 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO004','INSURANCE','보험 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO005','FX','환전/외환 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO006','ACCOUNT','계좌 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO007','INTERNET_BANKING','인터넷/모바일뱅킹 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO008','FEE','수수료/요금 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO009','COMPLAINT','민원/불만 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO010','GENERAL','일반 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO011','SECURITY','보안/사기 예방 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','CO012','LOST','분실/재발급 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA001','MERCHANT','일반 가맹점','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA002','FRANCHISE','프랜차이즈 제휴처','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA003','INSURANCE','보험사 제휴처','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA004','FINANCIAL','금융기관 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA005','SERVICE','서비스업 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA006','TRANSPORT','교통/모빌리티 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA007','RETAIL','유통/마트/백화점 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA008','FOOD','음식/카페 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','PA009','ETC','기타 제휴처','제휴사 타입', CURRENT_TIMESTAMP);


INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','CS001','EFFECTIVE','유효', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','CS002','EXPIRED','만기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','CS003','TERMINATED','해지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','CS004','SUSPENDED','효력 정지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','AP001','PENDING','대기 중', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','AP002','APPROVED','승인', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','AP003','REJECTED','거부', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','AP004','CANCELED','취소', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','AS001','ACTIVE','활성화', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','AS002','INACTIVE','비활성화', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','AS003','DORMANT','휴면', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','AS004','FROZEN','법적동결', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','AS005','CLOSED','해지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG001','CAPITAL','수도권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG002','CENTRAL','충청권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG003','HONAM','호남권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG004','YEONGNAM','영남권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG005','GANGWON','강원권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG006','JEJU','제주권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','RG007','OTHER','기타/해외', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX001','GENERATED','생성', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX002','BILLED','발행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX003','ONGOING','진행 중', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX004','PAID','납부 완료', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX005','REFUND','환불', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','TX006','CLOSED','종료', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK001','FARM','은행팜', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK002','SHINHAN','신한은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK003','KOOKMIN','국민은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK004','WOORI','우리은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK005','HANA','하나은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK006','NONGHYUP','농협은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK007','IBK','기업은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK008','SC','SC 제일은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK009','KDB','산업은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK010','SUHYUP','수협은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK011','KAKAO','카카오뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK012','K_BANK','케이뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK013','TOSS','토스뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK014','POST','우체국은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK015','JEJU','제주은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK016','GWANGJU','광주은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK017','DAEGU','대구은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK018','BUSAN','부산은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK019','KYUNGNAM','경남은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','BK020','JEONBUK','전북은행', CURRENT_TIMESTAMP);
