# 상위 공통 코드
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CS','CONTRACT_STATUS','계약 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AP','AUTHORIZATION_PROCESS','승인 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AS','ACCOUNT_STATUS','계좌 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('RG','REGION','지역', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('TX','TRANSACTION','거래 상태', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('BK','BANK','은행 코드', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CD','CARD','카드', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('AC','ACCOUNT','계좌', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('BR','BRANCH','지점', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('PD','PRODUCT','상품', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('OD','OVERDUE','연체', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('IN','INSURANCE','보험', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('LN','LOAN','대출', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('RT','RATE','금리', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('FX','FOREIGN_EXCHANGE','외환', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('DO','DEPOSIT','예/적금', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('CO','COUNSELING','상담', CURRENT_TIMESTAMP);
INSERT INTO super_code(sc_cd_id, sc_cd_nm, sc_cd_des, sc_created_at) VALUES ('PA','PARTNER','제휴사', CURRENT_TIMESTAMP);

# 하위 공통 코드
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','001','TRANSPORTATION CARD','교통카드','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','002','CASHBACK','캐시백','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','003','POINT','포인트','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','004','OVERSEAS','해외 결제','옵션코드', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','006','ACTIVE','정상','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','007','SUSPENDED','거래정지','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','008','LOST','분실','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','009','CANCELLED','해지','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','010','EXPIRED','만료','카드 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','016','SCHEDULED','예정','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','017','BILLED','청구 완료','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','018','PAID','납부 완료','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','019','OVERDUE','연체','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','020','REFUNDED','환불','회차 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','026','GENERATED','생성','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','027','BILLED','발행','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','028','PAID','완납','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','029','OVERDUE','연체','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CD','030','CLOSED','종료','청구 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','001','BOTH','제한 없음','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','002','DEPOSIT_ONLY','입금 전용','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('AC','003','WITHDRAW_ONLY','출금 전용','계좌 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','001','OPEN','영업중','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','002','CLOSED','영업종료','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('BR','003','SUSPENDED','휴점','영업 상태', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','001','PAPER','지류','서류 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','002','ELECTRONIC','디지털','서류 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','006','DEPOSIT','예적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','007','LOAN','대출','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','008','CARD','카드','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PD','009','INSURANCE','보험','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','001','LOAN','대출','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','002','CARD','카드','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('OD','003','INSURANCE','보험','연체 주체', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','001','TERMINATED','해지','해지/만기 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','002','EXPIRED','만기','해지/만기 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','006','WHOLE_LIFE','종신보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','007','TERM_LIFE','정기보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','008','ENDOWMENT','저축성/만기환급형 보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','009','UNIVERSAL','유니버셜보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','010','VARIABLE_LIFE','변액보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','011','ANNUITY','연금보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','012','ANNUITY_VARIABLE','변액연금보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','013','HEALTH','건강보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','014','CANCER','암보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','015','CRITICAL_ILLNESS','중대질병(CI) 보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','016','MEDICAL','의료실비보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','017','ACCIDENT','상해보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','018','DRIVER','운전자보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','019','TRAVEL','여행자보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','020','FIRE','화재보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','021','HOME','주택/가재도구보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','022','AUTO','자동차보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','023','PET','반려동물보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','024','LIABILITY','배상책임보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('IN','025','GROUP','단체보험','보험 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','001','EQUAL_INSTALLMENT','원리금 균등 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','002','EQUAL_PRINCIPAL','원금 균등 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','003','LUMP_SUM','만기 일시 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','004','GRACE','거치식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','005','MIXED','혼합 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','006','REVOLVING','자유 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','007','STEP_UP','체중식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('LN','008','STIP_DOWN','체감식 상환','상환 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','001','DISCOUNT','우대금리','금리 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','002','ADDITIONAL','가산금리','금리 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','006','DEPOSIT','예/적금','금리 적용 상품 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('RT','007','LOAN','대출','금리 적용 상품 유형', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','001','EXCHANGE','환전','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','002','RE_EXCHANGE','재환전','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','003','TRANSFER','이체','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','004','PURCHASE','매입','거래 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','006','TUITION_EXPENSES','유학 경비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','007','LIVING_EXPENSES','해외 체재비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','008','TRAVEL_EXPENSES','여행 경비','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','009','GIFT/DONATION_REMITTANCE','증여 송금','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','010','TRADE_SETTLEMENT','무역거래','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','011','OVERSEAS_DIRECT_INV','해외 직접 투자','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','012','REAL_ESTATE_ACQ','부동산 취급','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('FX','013','OVERSEAS_DEPOSIT','해외 예금','거래 목적', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','001','DEMAND_DEPOSIT','요구불 예금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','002','TIME_DEPOSIT','정기 예금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','003','FIXED_SAVING','정기 적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','004','FREE_SAVING','자유 적금','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','016','DAY','일','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','017','MONTH','월','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','018','YEAR','년','이자 계산 단위', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','021','MATURITY','만기 지급','이자 지급 주기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','022','MONTHLY','월 지급','이자 지급 주기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','026','SIMPLE','단리','이자 계산 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('DO','027','COMPOUND','복리','이자 계산 방식', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','001','LOAN','대출 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','002','DEPOSIT','예적금 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','003','CARD','카드 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','004','INSURANCE','보험 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','005','FX','환전/외환 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','006','ACCOUNT','계좌 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','007','INTERNET_BANKING','인터넷/모바일뱅킹 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','008','FEE','수수료/요금 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','009','COMPLAINT','민원/불만 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','010','GENERAL','일반 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','011','SECURITY','보안/사기 예방 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('CO','012','LOST','분실/재발급 상담','상품 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','001','MERCHANT','일반 가맹점','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','002','FRANCHISE','프랜차이즈 제휴처','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','003','INSURANCE','보험사 제휴처','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','004','FINANCIAL','금융기관 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','005','SERVICE','서비스업 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','006','TRANSPORT','교통/모빌리티 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','007','RETAIL','유통/마트/백화점 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','008','FOOD','음식/카페 제휴사','제휴사 타입', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_category_nm, cc_created_at) VALUES ('PA','009','ETC','기타 제휴처','제휴사 타입', CURRENT_TIMESTAMP);


INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','001','EFFECTIVE','유효', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','002','EXPIRED','만기', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','003','TERMINATED','해지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('CS','004','SUSPENDED','효력 정지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','001','PENDING','대기 중', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','002','APPROVED','승인', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','003','REJECTED','거부', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AP','004','CANCELED','취소', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','001','ACTIVE','활성화', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','002','INACTIVE','비활성화', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','003','DORMANT','휴면', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','004','FROZEN','법적동결', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('AS','005','CLOSED','해지', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','001','CAPITAL','수도권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','002','CENTRAL','충청권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','003','HONAM','호남권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','004','YEONGNAM','영남권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','005','GANGWON','강원권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','006','JEJU','제주권', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('RG','007','OTHER','기타/해외', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','001','GENERATED','생성', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','002','BILLED','발행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','003','ONGOING','진행 중', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','004','PAID','납부 완료', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','005','REFUND','환불', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('TX','006','CLOSED','종료', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','001','FARM','은행팜', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','002','SHINHAN','신한은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','003','KOOKMIN','국민은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','004','WOORI','우리은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','005','HANA','하나은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','006','NONGHYUP','농협은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','007','IBK','기업은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','008','SC','SC 제일은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','009','KDB','산업은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','010','SUHYUP','수협은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','011','KAKAO','카카오뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','012','K_BANK','케이뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','013','TOSS','토스뱅크', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','014','POST','우체국은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','015','JEJU','제주은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','016','GWANGJU','광주은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','017','DAEGU','대구은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','018','BUSAN','부산은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','019','KYUNGNAM','경남은행', CURRENT_TIMESTAMP);
INSERT INTO common_code(sc_cd_id, cc_cd_id, cc_cd_nm, cc_cd_des, cc_created_at) VALUES ('BK','020','JEONBUK','전북은행', CURRENT_TIMESTAMP);